# Generated by Django 5.0.1 on 2025-08-23 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0014_alter_dailyevent_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyevent',
            name='important',
            field=models.BooleanField(default=False),
        ),
    ]
